# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AppConfig
version:      1.63
version_from: lib/AppConfig.pm
installdirs:  site
requires:
    File::HomeDir:                 0.57
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
